# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(200, 0, 400, 41))
        self.textEdit.setObjectName("textEdit")
        self.label_img = QtWidgets.QLabel(self.centralwidget)
        self.label_img.setGeometry(QtCore.QRect(10, 50, 512, 512))
        self.label_img.setObjectName("label_img")
        self.pushButton_getImg = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_getImg.setGeometry(QtCore.QRect(560, 60, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_getImg.setFont(font)
        self.pushButton_getImg.setObjectName("pushButton_getImg")
        self.pushButton_predict = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_predict.setGeometry(QtCore.QRect(560, 200, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_predict.setFont(font)
        self.pushButton_predict.setObjectName("pushButton_predict")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(560, 300, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox_modelSelect = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_modelSelect.setGeometry(QtCore.QRect(560, 170, 131, 22))
        self.comboBox_modelSelect.setObjectName("comboBox_modelSelect")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(560, 150, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_res = QtWidgets.QLabel(self.centralwidget)
        self.label_res.setGeometry(QtCore.QRect(560, 320, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_res.setFont(font)
        self.label_res.setObjectName("label_res")
        self.pushButton_batchPredict = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_batchPredict.setGeometry(QtCore.QRect(560, 460, 231, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_batchPredict.setFont(font)
        self.pushButton_batchPredict.setObjectName("pushButton_batchPredict")
        self.label_isDetect = QtWidgets.QLabel(self.centralwidget)
        self.label_isDetect.setGeometry(QtCore.QRect(560, 110, 47, 13))
        self.label_isDetect.setText("")
        self.label_isDetect.setObjectName("label_isDetect")
        self.label_isDetectbatch = QtWidgets.QLabel(self.centralwidget)
        self.label_isDetectbatch.setGeometry(QtCore.QRect(560, 510, 47, 13))
        self.label_isDetectbatch.setText("")
        self.label_isDetectbatch.setObjectName("label_isDetectbatch")
        self.pushButton_summary = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_summary.setGeometry(QtCore.QRect(630, 530, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.pushButton_summary.setFont(font)
        self.pushButton_summary.setObjectName("pushButton_summary")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuResult_View = QtWidgets.QMenu(self.menubar)
        self.menuResult_View.setObjectName("menuResult_View")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuResult_View.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">MRI Brain Tumor Classificiation</span></p></body></html>"))
        self.label_img.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_getImg.setText(_translate("MainWindow", "Get Image"))
        self.pushButton_predict.setText(_translate("MainWindow", "Predict"))
        self.label_2.setText(_translate("MainWindow", "Result :"))
        self.label_3.setText(_translate("MainWindow", "Model Select :"))
        self.label_res.setText(_translate("MainWindow", "..."))
        self.pushButton_batchPredict.setText(_translate("MainWindow", "Batch Prediction"))
        self.pushButton_summary.setText(_translate("MainWindow", "See Summary"))
        self.menuResult_View.setTitle(_translate("MainWindow", "Result View"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
